name: mein-projekt1

on:
env:
   PYTHON_VERSION: "3.12"
   APP_ENV: staging
push:
pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          ${{ env.PYTHON_VERSION }}

      - name: Pip-Cache
        uses: actions/cache@v4
        with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }} restore-keys: ${{ runner.os }}-pip

      - name: Dependencies installieren
        run: python -m pip install -r requirements.txt

      - name: Tests ausführen
        run: python -m pytest -v

      - name: Python-Version anzeigen
        run: python --version
        
      - name: Paket bauen
        run : |
          mkdir —p build 
          python —m zipfile —c build/app.zip src / 
